import AppleNavbar from "@/components/navbar";
import "./globals.css";
import Footer from "@/components/footer";
import Battareya from "@/components/home/battareya";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <AppleNavbar/>
        {children}
        <Battareya/>
        <Footer/>
      </body>
    </html>
  );
}
